# Generated by Django 4.0.4 on 2022-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveniment_template',
            name='an_incepere',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)]),
        ),
        migrations.AlterField(
            model_name='eveniment_template',
            name='luna_incepere',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='eveniment_template',
            name='recurenenta',
            field=models.CharField(choices=[('saptamanal', 'saptamanal'), ('lunar', 'lunar'), ('anual', 'anual'), ('2ani', '2ani')], max_length=100),
        ),
        migrations.AlterField(
            model_name='eveniment_template',
            name='zi_incepere',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28)]),
        ),
    ]
