# Generated by Django 4.0.4 on 2022-05-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENTS', '0003_alter_eveniment_data_finalizare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveniment',
            name='data_finalizare',
            field=models.DateField(blank=True),
        ),
    ]
