# Generated by Django 4.0.4 on 2022-06-25 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EVENTS', '0004_alter_eveniment_data_finalizare'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveniment_template',
            name='responsabil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eveniment_temp', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eveniment_template',
            name='proiect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenimente', to='PROJECTS.proiect'),
        ),
    ]
