# Generated by Django 4.0.4 on 2022-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proiect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30, unique=True)),
                ('id_proiect', models.IntegerField(unique=True)),
                ('descriere', models.CharField(max_length=100)),
            ],
        ),
    ]
